// Copyright 2026 Radio Sound, Inc.
// Licensed under the Apache License, Version 2.0.

apply plugin: "com.android.application"

android {
    namespace "com.android.car.libraries.templates.host"
    compileSdk 35

    defaultConfig {
        applicationId "com.android.car.libraries.templates.host"
        minSdk 30
        targetSdk 35
        versionCode 1
        versionName "0.1.0"
    }
}

dependencies {
    implementation "androidx.car.app:app-automotive:1.7.0"
}
